export const SSM_KEYS = {
  LANCEDB_STORAGE_BUCKET_NAME: '/idp-v2/lancedb/storage/bucket-name',
  LANCEDB_LOCK_TABLE_NAME: '/idp-v2/lancedb/lock/table-name',
  DOCUMENT_STORAGE_BUCKET_NAME: '/idp-v2/document-storage/bucket-name',
  SESSION_STORAGE_BUCKET_NAME: '/idp-v2/session-storage/bucket-name',
  AGENT_STORAGE_BUCKET_NAME: '/idp-v2/agent-storage/bucket-name',
  MODEL_ARTIFACTS_BUCKET_NAME: '/idp-v2/model-artifacts/bucket-name',
  BACKEND_TABLE_NAME: '/idp-v2/backend/table-name',
  LANCEDB_EXPRESS_BUCKET_NAME: '/idp-v2/lancedb/express/bucket-name',
  LANCEDB_EXPRESS_AZ_ID: '/idp-v2/lancedb/express/az-id',
  VPC_ID: '/idp-v2/vpc/id',
  AGENT_RUNTIME_ARN: '/idp-v2/agent/runtime-arn',
  BIDI_AGENT_RUNTIME_ARN: '/idp-v2/bidi-agent/runtime-arn',
  PADDLEOCR_EC2_INSTANCE_ID: '/idp-v2/paddleocr/ec2-instance-id',
  BACKEND_URL: '/idp-v2/backend/url',
  SEARCH_MCP_FUNCTION_ARN: '/idp-v2/mcp/search/function-arn',
  SEARCH_MCP_ROLE_ARN: '/idp-v2/mcp/search/role-arn',
  ELASTICACHE_ENDPOINT: '/idp-v2/elasticache/endpoint',
} as const;
